### ISSUE TITLE
Load every font in TTC collections, not just the first one

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/fontdiff#6]
fontdiff generates an output when presented with the TTC fonts.

for example, 
build/out/Default/fontdiff \
	--before /Users/marekj/Downloads/SourceHanSerif2ND-Regular.ttc \
	--after /Users/marekj/Downloads/ThirdInterimDrop/OTC/SourceHanSerif3RD-Regular.ttc \
	--specimen specimen/zh-cn.html \
	--out specimen/SourceHanSerif3RD-Regular.pdf

generates specimen/SourceHanSerif3RD-Regular.pdf

However, this TTC has three fonts [0 through 2 (inclusive)]. Does it pick font 0 always? If that's the case then I want ability to specify which font I want. Is it driven by the lang my html?

Just curious.

**Comment by marekjez86** [comment]
Note that I filed https://github.com/googlei18n/fontreport/issues/7 ; if there's something that needs to be done please coordinate with the https://github.com/googlei18n/fontreport component owner so the tools look like they have a common interface.

**Comment by brawer** [comment]
@marekjez86, can you send me these TTCs over e-mail?

**Comment by jamesgk** [comment]
@brawer, have you thought what this common interface should look like? What if we just had alternative arguments `--before-ttc / --after-ttc` which must be followed by a font and an index?

**Comment by marekjez86** [comment]
please search for emails with subject:"ttc re:
https://github.com/googlei18n/fontdiff/issues/6"
I sent two because these are large files


On Fri, Jul 1, 2016 at 4:51 PM, Sascha Brawer <notifications@github.com>
wrote:

> @marekjez86 <https://github.com/marekjez86>, can you send me these TTCs
> over e-mail?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/googlei18n/fontdiff/issues/6#issuecomment-229981877>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMtJf_pGBqju8il_-BipCh-6vdIrTPaxks5qRTdzgaJpZM4JC1An>
> .
>



-- 

Marek Z Jeziorek [ 老马 ] | marekj@google.com | 312 725-6958

**Comment by brawer** [comment]
Apologies for the delay; I was on vacation. Actually, the `--before` and `--after` arguments can take multiple fonts, not just a single file. Why? Let me explain.

* When fontdiff renders an HTML file, it considers CSS attributes such as `font-family` and `font-weight` to look for a matching font. This allows diffing document that use multiple families and styles. For example, if the given HTML sample has spans with `font-weight:800`, fontdiff (just like a browser) may well use a different physical font file than for a span with `font-weight:200`. This wouldn’t work if the tool just took a single font file as its input.

* Perhaps more importantly, if `--before` and `--after` were restricted to single physical files, the “Noto” font could not be diffed on real-world text samples like the [UDHR corpus](http://www.unicode.org/udhr/translations.html). Since Noto is split across dozens of script-specific files, fontdiff (just like a browser) will often use different physical font files for a single span of Unicode text. For example, the text of the [Cherokee sample](http://www.unicode.org/udhr/d/udhr_chr_cased.html) is mostly in the Cherokee script, but it also contains punctuation and numbers which are not part of NotoSansCherokee. To render such HTML files in the “Noto” font, fontdiff (just like a browser) thus has to combine glyphs from multiple physical font files. Again, this wouldn’t work if the tool just took a single font file as its input.

For these reasons, I don’t think it would be a good idea to add an explicit argument for font indices. Instead, if a physical font file contains multiple fonts (as is the case for *.ttc files), I think fontdiff should load them all, and then consider them all in its font resolution. Currently, it loads only the first face in a file. Fixing this should be quite easy.

Now, for SourceSansCJK or NotoSansCJK, it won’t actually make any difference. These TTC collections contain the exact same fonts three times, just with different defaults for localized letterforms aka `loca` features. Since fontdiff (just like a browser) makes localized letterforms accessible via the HTML `lang` attribute, the following sample should work even with current fontdiff:

```html
<html>
  <div>
    <span lang="ja">今</span>
    <span lang="zh-Hans">今</span>
    <span lang="zh-Hant">今</span>
  </div>
</html>
```

However, fontdiff (_other_ than a browser) currently always selects the Japanese letterform for the above snippet. There’s actually a workaround: if you pass `lang="zh-Hani"`, fontdiff will use the Chinese instead of the Japanese letterform. But this is not how browsers work, so it needs to be fixed. The fix is a bit tricky, but doable. I’ll file a separate bug for it.

**Comment by jamesgk** [comment]
Right, that makes sense. I guess we want to do the same (treating a TTC argument the exact same as multiple TTF arguments) for notodiff and fontreport.

**Comment by brawer** [comment]
See https://github.com/googlei18n/fontdiff/issues/7 for the mentioned bug.

**Comment by brawer** [comment]
@marekjez86, you can now pass `*.ttc` and `*.otc` files; fontdiff will load all contained fonts. For example, here’s a screenshot with different weights loaded from NotoSansCJK.ttc:

<img width="288" alt="notosanscjk-multiweight" src="https://cloud.githubusercontent.com/assets/1527880/17193430/cf627e5c-5407-11e6-906c-d8f7830e9a19.png">
